general.import = ["~/.config/alacritty/catppuccin-frappe.toml"]

window = { opacity = 0.69, padding = { x = 8, y = 4 } }

font.size = 11.25

font.normal = { family = "JetBrainsMono Nerd Font Mono" }
font.italic = { style = "SemiBold Italic" }
font.bold = { style = "ExtraBold" }
font.bold_italic = { style = "ExtraBold Italic" }

terminal = { shell = "fish" }
