general.import = ["~/.config/alacritty/catppuccin-frappe.toml"]

window = { opacity = 0.9, padding = { x = 8, y = 4 } }

font = { normal = { family = "JetBrainsMono Nerd Font Mono" } }

terminal = { shell = "fish" }
